import { Product } from './store/table.state';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Laptop',
    description: 'A high-quality laptop.',
    price: 1000,
    category: 'ELECTRONICS',
  },
  {
    id: 2,
    name: 'Jeans',
    description: 'Comfortable blue jeans.',
    price: 50,
    category: 'CLOTHING',
  },
  {
    id: 3,
    name: 'Apples',
    description: 'Fresh red apples.',
    price: 5,
    category: 'FOOD',
  },
  {
    id: 4,
    name: 'Desk Chair',
    description: 'Ergonomic office chair.',
    price: 150,
    category: 'FURNITURE',
  },
  {
    id: 5,
    name: 'Bluetooth Speaker',
    description: 'Portable bluetooth speaker.',
    price: 30,
    category: 'ELECTRONICS',
  },
  {
    id: 6,
    name: 'Sneakers',
    description: 'Running shoes in various colors.',
    price: 65,
    category: 'CLOTHING',
  },
  {
    id: 7,
    name: 'Electric Kettle',
    description: 'Stainless steel electric kettle.',
    price: 45,
    category: 'APPLIANCES',
  },
  {
    id: 8,
    name: 'Camping Tent',
    description: 'Waterproof 4-person tent.',
    price: 120,
    category: 'OUTDOOR',
  },
  {
    id: 9,
    name: 'Wall Clock',
    description: 'Stylish wall clock with quartz movement.',
    price: 25,
    category: 'HOME DECOR',
  },
  {
    id: 10,
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat.',
    price: 20,
    category: 'FITNESS',
  },
  {
    id: 11,
    name: 'Coffee Machine',
    description: 'Espresso coffee machine with milk frother.',
    price: 220,
    category: 'APPLIANCES',
  },
  {
    id: 12,
    name: 'Leather Wallet',
    description: "Durable men's leather wallet.",
    price: 35,
    category: 'ACCESSORIES',
  },
  {
    id: 13,
    name: 'Reading Lamp',
    description: 'LED reading lamp with adjustable brightness.',
    price: 40,
    category: 'HOME DECOR',
  },
  {
    id: 14,
    name: 'Hand Sanitizer',
    description: 'Alcohol-based hand sanitizer.',
    price: 5,
    category: 'HEALTH',
  },
  {
    id: 15,
    name: 'Mountain Bicycle',
    description: '21-speed mountain bicycle.',
    price: 350,
    category: 'OUTDOOR',
  },
  {
    id: 16,
    name: 'Sunglasses',
    description: 'UV-protected polarized sunglasses.',
    price: 55,
    category: 'ACCESSORIES',
  },
  {
    id: 17,
    name: 'Bluetooth Earphones',
    description: 'Wireless earphones with noise-cancellation.',
    price: 80,
    category: 'ELECTRONICS',
  },
  {
    id: 18,
    name: 'Cutlery Set',
    description: 'Stainless steel cutlery set for 4.',
    price: 45,
    category: 'KITCHEN',
  },
  {
    id: 19,
    name: 'Bed Sheet Set',
    description: 'King-sized cotton bed sheet with two pillow covers.',
    price: 70,
    category: 'HOME DECOR',
  },
  {
    id: 20,
    name: 'Running Watch',
    description: 'Smartwatch with GPS and heart rate monitoring.',
    price: 230,
    category: 'FITNESS',
  },
  {
    id: 21,
    name: 'Wireless Mouse',
    description: 'Ergonomic design with adjustable DPI.',
    price: 30,
    category: 'ELECTRONICS',
  },
  {
    id: 22,
    name: 'Kitchen Mixer',
    description: 'High-speed blender with multiple attachments.',
    price: 150,
    category: 'KITCHEN',
  },
  {
    id: 23,
    name: 'Yoga Mat',
    description: 'Anti-slip yoga mat.',
    price: 20,
    category: 'FITNESS',
  },
  {
    id: 24,
    name: 'Face Serum',
    description: 'Vitamin C infused face serum.',
    price: 25,
    category: 'SKINCARE',
  },
  {
    id: 25,
    name: 'Desk Organizer',
    description: 'Wooden desk organizer with compartments.',
    price: 35,
    category: 'OFFICE',
  },
  {
    id: 26,
    name: 'Camping Tent',
    description: 'Waterproof 4-person tent.',
    price: 120,
    category: 'OUTDOOR',
  },
  {
    id: 27,
    name: 'Travel Pillow',
    description: 'Memory foam neck pillow for comfortable travel.',
    price: 15,
    category: 'TRAVEL',
  },
  {
    id: 28,
    name: 'Digital Camera',
    description: 'High-resolution digital camera with optical zoom.',
    price: 500,
    category: 'ELECTRONICS',
  },
  {
    id: 29,
    name: 'Gardening Tools',
    description: 'Set of essential gardening tools.',
    price: 45,
    category: 'GARDEN',
  },
  {
    id: 30,
    name: 'Thermal Flask',
    description: 'Double-walled thermal flask for hot and cold beverages.',
    price: 25,
    category: 'KITCHEN',
  },
];
